### base route
GET {{baseUrl}}

### register a user return status 
# return status
# 201 -> successfully registered
POST {{baseUrl}}/auth/register
content-type: application/json

{
 "email": "testing-user-42@yopmaill.com",
 "username": "bllabla-ok",
 "passwd": "Allt.xp-c0hrhhn@yopmaill.com",
 "confirmPasswd": "Allt.xp-c0hrhhn@yopmaill.com",
 "firstName": "GUESTs",
 "lastName": "Blablas"
}


### verify and activate user account
# return status 200 -> sucessfully verified
POST {{baseUrl}}/auth/verify/{{validationToken}}
Content-Type: application/json


### login user
# return status 200 -> successfully logged in
POST {{baseUrl}}/auth/login
content-type: application/json

{
 "username": "user42",
 "passwd": "Allt.xp-c0hrhhn@yopmaill.comLL"
}

### get current user profile
# return status 200 -> successfully fetched user profile
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### check user identifier availability
# return status 200 -> successfully checked user identifier availability
POST {{baseUrl}}/users/check-identifier
Content-Type: application/json  

{
  "field": "username",
  "value": "cool"
}

### refresh access token
# return status 201 -> successfully refreshed access token
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### reset password
# return status 200 -> successfully sent reset password link
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "testing-user-42@yopmail.com"
}

### confirm reset password
# return status 200 -> success
POST {{baseUrl}}/auth/confirm-reset-password/{{refreshToken}}
Content-Type: application/json


### create new password
# return status 200 -> success
POST {{baseUrl}}/auth/create-new-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "passwd": "Allt.xp-c0hrhhn@yopmaill.comLLLL",
  "confirmPasswd": "Allt.xp-c0hrhhn@yopmaill.comLLLL"
}

### logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}} {{refreshToken}}
