### base route
GET http://localhost:5000/api/v1

### register a user
POST http://localhost:5000/api/v1/auth/register
content-type: application/json

{
 "email": "allt.xp-c0hrhhn@yopmail.com",
 "username": "guestt-422",
 "passwd": "Allt.xp-c0hrhhn@yopmail.com",
 "confirmPasswd": "Allt.xp-c0hrhhn@yopmail.com",
 "firstName": "GUEST",
 "lastName": "Blabla"
}
