### base route
GET {{baseUrl}}

### register a user
POST {{baseUrl}}/auth/register
content-type: application/json

{
 "email": "alt.c9-2xeyqyo@yopmail.com",
 "username": "blabla-1",
 "passwd": "Allt.xp-c0hrhhn@yopmail.com",
 "confirmPasswd": "Allt.xp-c0hrhhn@yopmail.com",
 "firstName": "GUEST",
 "lastName": "Blabla"
}

### activate user account
POST {{baseUrl}}/auth/activate/{{validationToken}}
