services:
  db:
    image: postgres:13-alpine
    networks:
      - matcha-network
    ports:
      - '5432:5432'
    env_file:
      - ./packages/api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
    - matcha-network
    ports:
    - '6379:6379'
    command: ['redis-server', '--save', '', '--appendonly', 'no']

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - '127.0.0.1:5000:5000'
    depends_on:
      - db
      - redis
    env_file:
      - ./packages/api/.env
    networks:
      - matcha-network
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - ./packages/shared:/usr/src/app/packages/shared
      - /usr/src/app/node_modules

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '5173:5173'
    env_file:
      - ./packages/front/.env
    networks:
      - matcha-network
    volumes:
      - ./packages/front:/usr/src/app/packages/front
      - ./packages/shared:/usr/src/app/packages/shared
      - /usr/src/app/node_modules

volumes:
  pgdata:

networks:
  matcha-network:
    driver: bridge
