services:
  db:
    image: postgres:13-alpine
    networks:
      - matcha-network
    env_file:
      - ./packages/api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis:7-alpine
    networks:
      - matcha-network
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
  back:
    build:
      context: .
      dockerfile: Dockerfile.back.prod
    depends_on:
      - db
      - redis
    env_file:
      - ./packages/api/.env
    networks:
      - matcha-network
    restart: unless-stopped
  front:
    build:
      context: .
      dockerfile: Dockerfile.front.prod
    networks:
      - matcha-network
      - proxy-network 
    restart: unless-stopped

volumes:
  pgdata:

networks:
  matcha-network:
  proxy-network:
    external: true
