services:
  db:
    image: postgres:13-alpine
    networks:
      - matcha-network
    ports:
      - '5432:5432'
    env_file:
      - ./packages/api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - '127.0.0.1:5000:5000'
    depends_on:
      - db
    env_file:
      - ./packages/api/.env
    networks:
      - matcha-network
    develop:
      watch:
        - action: rebuild
          path: ./packages/api
          ignore:
            - node_modules/

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '5173:5173'
    env_file:
      - ./packages/front/.env
    networks:
      - matcha-network
    develop:
      watch:
        - action: rebuild
          path: ./packages/front

volumes:
  pgdata:

networks:
  matcha-network:
    driver: bridge
