# Use Node 20 Alpine
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY packages/front/package*.json ./packages/front/
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev:front"]
