export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  RESET_PASSWORD_WISHED_BY_USER = 'RESET_PASSWORD_WISHED_BY_USER',
  UPLOAD_USER_IMAGE = 'UPLOAD_USER_IMAGE',
  USER_IMAGE_UPLOADED = 'USER_IMAGE_UPLOADED',
}
