export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  RESET_PASSWORD_WISHED_BY_USER = 'RESET_PASSWORD_WISHED_BY_USER',
  UPLOAD_USER_IMAGE = 'UPLOAD_USER_IMAGE',
  USER_IMAGE_DELETED = 'USER_IMAGE_DELETED',
}

export const SocketEvents = {
  CONNECTION: 'connection',
  DISCONNECT: 'logout',
  USER_IMAGE_UPLOADED: 'user_image_uploaded',
} as const;
