export enum CreateNewPasswordError {
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  UNKNOWN_ERROR = 'UNKNOW_ERROR',
  MIS_MATCH_PASSWORD = 'MIS_MATCH_PASSWORD',
}
