export enum UpdateUserProfileError {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERNAME_ALREADY_EXISTS = 'USER_NAME_ALREADY_EXISTS',
  EMAIL_AREDAY_EXISTS = 'EMAIL_AREDAY_EXISTS',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
