export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  RESET_PASSWORD_WISHED_BY_USER = 'RESET_PASSWORD_WISHED_BY_USER',
  USER_IMAGE_DELETED = 'USER_IMAGE_DELETED',
  USER_INTERACTION_ADDED = 'USER_INTERACTION_ADDED',
  USER_DISCONNECTED = 'USER_DISCONNECTED',
}
