# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: matcha CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: matcha ci
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    - name: Lint
      run: npm lint
    - name: build
      run: npm build --if-present
    - name: test front
      run: npm test:front
    - name: test back
      run: npm test:back

